###
### POST request to login API
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "username": "admi",
    "password": "admin123"
}
###

### GET request to /api/me (requires authentication)
GET http://localhost:8000/api/me
Authorization: Bearer 1|jubtOAp3sW4pdjl5TlioVL24rRC6rxy2Z4CKqxP9cc9a91d

###
