###
### POST request to login API
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}
###

### GET request to /api/me (requires authentication)
GET http://localhost:8000/api/me
Authorization: Bearer 1|H60clBaCpfUqx9Bmpx2gMnHxuxXPWA0M7OC2PI4gbd3dbd56

###
